    #base    "../../#users/custom/resource/ui/hudammoweapons.res"
    #base    "../../#customization/_enabled/bh_player_largeammo.res"
    #base    "../../#customization/_enabled/bh_player_ammobox.res"
    #base    "../../_budhud/resource/ui/hudammoweapons.res"
    #base    "../../_tf2hud/resource/ui/hudammoweapons.res"