    #base    "../../#customization/_enabled/bh_player_hideclassmodel.res"
    #base    "../../#customization/_enabled/bh_player_teamindicator.res"
    #base    "../../#customization/_enabled/bh_crosshairs.res"
    #base    "../../_budhud/resource/ui/hudplayerclass.res"
    #base    "../../_tf2hud/resource/ui/hudplayerclass.res"