    #base    "../../#users/custom/resource/ui/hudplayerclass.res"
    #base    "../../#users/custom/#customization/_enabled/bh_player_hideclassmodel.res"
    #base    "../../#users/custom/#customization/_enabled/bh_player_teamindicator.res"
    #base    "../../_budhud/resource/ui/hudplayerclass.res"
    #base    "../../_tf2hud/resource/ui/hudplayerclass.res"