    #base    "../../#customization/_enabled/bh_menu_hidefavorites.res"
    #base    "../../#customization/_enabled/bh_menu_hidenews.res"
    #base    "../../#customization/_enabled/bh_menu_hidegif.res"
    #base    "../../_budhud/resource/ui/mainmenuoverride_preloading.res"
    #base    "../../_budhud/resource/ui/mainmenuoverride.res"
    #base    "../../_tf2hud/resource/ui/mainmenuoverride.res"