    #base    "../../#users/custom/resource/ui/spectatortournament.res"
    #base    "../../#users/custom/#customization/_enabled/bh_tournamentpanels_castingessentials.res"
    #base    "../../#users/custom/#customization/_enabled/bh_tournamentpanels_allright.res"
    #base    "../../#users/custom/#customization/_enabled/bh_tournamentpanels_allleft.res"
    #base    "../../#users/custom/#customization/_enabled/bh_tournamentpanels_lower.res"
    #base    "../../_budhud/resource/ui/spectatortournament.res"
    #base    "../../_tf2hud/resource/ui/spectatortournament.res"