    #base    "../../#users/custom/resource/ui/statsummary.res"
    #base    "../../#users/custom/#customization/_enabled/bh_stats_customimage.res"
    #base    "../../#users/custom/#customization/_enabled/bh_stats_hidebackground.res"
    #base    "../../_budhud/resource/ui/statsummary.res"
    #base    "../../_tf2hud/resource/ui/statsummary.res"